print("Welcome to the School anaylasis")
print()
print("Location: Bayviewglen Upperschool")
print()
print()
print("**Data Collection**")
print()
print("1.Water fountains:")
waterfountain = int(input("Please input the amount of water fountains: "))
waterfountain_location = input("Please input the location of waterfountains: ")
waterfountain_condition = input("Please input the condition of waterfountains: ")
print()
print("2. Restrooms:")
restrooms = int(input("Please input the amount of retrooms: "))
restroom_location = input("Please input the locations of restrooms in the upperschool: ")
restroom_cleanliness = input("Please input the cleanliness of the restrooms: ")
print()
print("3.Classrooms: ")
classrooms = int(input("Please input the amount of classrooms: "))
waterfountainperclasroom = waterfountain / classrooms
restroomperclassroom = restrooms / classrooms
print()
print()
print("**Data Collected**")
print(f"1. Water Fountains:")
print(f"-Number: {waterfountain}")
print(f"-Location: {waterfountain_location}")
print(f"-Condition: {waterfountain_condition}")
print()
print(f"Restrooms:")
print(f"Number: {restrooms}")
print(f"Locations: {restroom_location}")
print(f"Cleanliness: {restroom_cleanliness}")
print()
print(f"Classrooms: ")
print(f"Total Number of Classrooms: {classrooms}")
print(f"Number of Water Fountains per Classroom: {waterfountainperclasroom}")
print(f"Number of Restrooms per Classroom: {restroomperclassroom}")
